export default {
  SET_LOADED: '[APP] SET_LOADED',
  WINDOW_RESIZE: '[APP] WINDOW_RESIZE',
  UPDATE_LOCATION: '[APP] UPDATE_LOCATION',
  SCROLL: '[APP] SCROLL',

  OPEN_PROJECT: '[PROJECTS] OPEN_PROJECT',
};
